//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOdevBaslangıc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resim
    {
        public int id { get; set; }
        public string ResimYolu { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
